name: frontend

on:
  push:
    branches: [master]
    paths: ["frontend/apps/remark42/**"]

  pull_request:
    branches: [master]
    paths: ["frontend/apps/remark42/**"]

jobs:
  tests:
    name: E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.15.1"

      - name: Start containers
        run: docker-compose -f compose-e2e-test.yml up -d --build

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i
        working-directory: ./frontend/tests

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend/tests

      - name: Run tests
        run: pnpm test
        working-directory: ./frontend/tests

      - uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
